/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import { BuButton as BuButton } from './components/bu-button/bu-button';

interface HTMLBuButtonElement extends BuButton, HTMLElement {
}
declare var HTMLBuButtonElement: {
  prototype: HTMLBuButtonElement;
  new (): HTMLBuButtonElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "bu-button": HTMLBuButtonElement;
  }
  interface ElementTagNameMap {
      "bu-button": HTMLBuButtonElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "bu-button": JSXElements.BuButtonAttributes;
      }
  }
  namespace JSXElements {
      export interface BuButtonAttributes extends HTMLAttributes {
        
          type?: string,
          value?: string,
          disabled?: boolean | "true" | "false",
          size?: string,
          outlined?: boolean | "true" | "false",
          inverted?: boolean | "true" | "false",
          hovered?: boolean | "true" | "false",
          focused?: boolean | "true" | "false",
          active?: boolean | "true" | "false",
          loading?: boolean | "true" | "false"
      }
  }
}

